name: Hexo Deploy

on:
    schedule:
        - cron: '*/10 * * * *'  # 每10分钟运行一次
    push:
        branches:
            - main

jobs:
    update-market:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 'lts/*'

            - name: Setup Environment
              run: |
                  corepack enable
                  yarn set version stable

            - name: Setup SSH
              env:
                  DEPLOY_KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }}
              run: |
                  mkdir -p ~/.ssh/
                  echo "$DEPLOY_KEY" > ~/.ssh/id_rsa
                  chmod 600 ~/.ssh/id_rsa
                  ssh-keyscan github.com >> ~/.ssh/known_hosts

            - name: Setup Market
              run: |
                  yarn

            - name: Configure Git
              env:
                  GIT_USER_NAME: ${{ secrets.GIT_USER_NAME }}
                  GIT_USER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
              run: |
                  git config --global user.name "$GIT_USER_NAME"
                  git config --global user.email "$GIT_USER_EMAIL"

            - name: Build and Deploy
              run: |
                  yarn scan

                  git add .
                  git stash

                  git fetch
                  git checkout pages || git checkout -b pages

                  git rm -rf .

                  cd public
                  cp -r . ..
                  cd ..
                  rm -rf public

                  git add .
                  git commit -m "Deploy to pages branch"

                  git push origin pages -f
