name: Update Market

on:
    schedule:
        - cron: '*/15 * * * *'
    push:
        branches:
            - main

jobs:
    update-market:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 'lts/*'

            - name: Setup Environment
              run: |
                  corepack enable
                  corepack install -g yarn

            - name: Setup SSH
              env:
                  DEPLOY_KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }}
              run: |
                  mkdir -p ~/.ssh/
                  echo "$DEPLOY_KEY" > ~/.ssh/id_rsa
                  chmod 600 ~/.ssh/id_rsa
                  ssh-keyscan github.com >> ~/.ssh/known_hosts

            - name: Setup Market
              run: |
                  yarn install --immutable
                  yarn build

            - name: Configure Git
              env:
                  GIT_USER_NAME: ${{ secrets.GIT_USER_NAME }}
                  GIT_USER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
              run: |
                  git config --global user.name "$GIT_USER_NAME"
                  git config --global user.email "$GIT_USER_EMAIL"

            - name: Sync
              env:
                  MONGODB_URI: ${{ secrets.MONGODB_URI }}
                  CATEGORIES_API_BASE: ${{ secrets.CATEGORIES_API_BASE }}
              run: |
                  yarn scan

            - name: Deploy to Pages Branch
              env:
                  CUSTOM_DOMAIN: ${{ secrets.CUSTOM_DOMAIN }}
              run: |
                  cp public/index.json /tmp/index.json

                  git checkout --orphan pages
                  git reset --hard

                  cp /tmp/index.json index.json

                  echo "" > .nojekyll

                  echo "$CUSTOM_DOMAIN" > CNAME

                  git remote set-url origin git@github.com:${GITHUB_REPOSITORY}.git

                  git add -f index.json .nojekyll
                  git add -f index.json CNAME .nojekyll
                  git commit -m "Update market" || true
                  git push -f origin pages

            - name: Push to CNB Repository
              env:
                  CNB_USER: ${{ secrets.CNB_USER }}
                  CNB_TOKEN: ${{ secrets.CNB_TOKEN }}
                  CNB_REPO: ${{ secrets.CNB_REPO }}
              run: |
                  git config --global credential.helper store
                  echo "https://${CNB_USER}:${CNB_TOKEN}@cnb.cool" > ~/.git-credentials
                  git remote add cnb https://cnb.cool/${CNB_REPO} || git remote set-url cnb https://cnb.cool/${CNB_REPO}
                  git push -f cnb main
