name: Update Market

on:
    schedule:
        - cron: '*/15 * * * *' # 每15分钟运行一次
    push:
        branches:
            - main
    workflow_dispatch: # 添加手动触发功能

jobs:
    update-market:
        runs-on: ubuntu-latest
        services:
            mongodb:
                image: mongo:4.4
                ports:
                    - 27017:27017
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 'lts/*'

            - name: Setup Environment
              run: |
                  corepack enable
                  corepack use yarn

            - name: Setup SSH
              env:
                  DEPLOY_KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }}
              run: |
                  mkdir -p ~/.ssh/
                  echo "$DEPLOY_KEY" > ~/.ssh/id_rsa
                  chmod 600 ~/.ssh/id_rsa
                  ssh-keyscan github.com >> ~/.ssh/known_hosts

            - name: Setup Market
              run: |
                  yarn

            - name: Configure Git
              run: |
                  git config --global user.name "github-actions[bot]"
                  git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

            - name: Sync
              env:
                  MONGODB_URI: mongodb://localhost:27017
                  CATEGORIES_API_BASE: ${{ secrets.CATEGORIES_API_BASE }}
                  INCREMENTAL_UPDATE: "false"
              run: |
                  yarn scan

            - name: Deploy to Pages Branch
              env:
                  CUSTOM_DOMAIN: ${{ secrets.CUSTOM_DOMAIN }}
              run: |
                  cp public/index.json /tmp/index.json

                  git checkout --orphan pages
                  git reset --hard

                  cp /tmp/index.json index.json

                  echo "" > .nojekyll

                  echo "$CUSTOM_DOMAIN" > CNAME

                  git remote set-url origin git@github.com:${GITHUB_REPOSITORY}.git

                  git add -f index.json .nojekyll
                  git add -f index.json CNAME .nojekyll
                  git commit -m "Update market" || true
                  git push -f origin pages
